from setuptools import setup

# read requirements.
# requirements = []
# with open("requirements.txt", 'rU') as reader:
#     for line in reader:
#         requirements.append(line.strip())

setup(name='PangenomeAlignmentGenerator',
      python_requires='>=3',
      version='201223',
      description='align SRAs to a pangenome reference genome generated by Roary',
      url='https://github.com/apsteinberg/PangenomeAlignmentGenerator',
      license='MIT',
      author='Asher Preska Steinberg',
      author_email='apsteinberg@nyu.edu',
      packages=['bin'],
      package_data={'': ['InvokeProkka', 'InvokeRoary', 'reorganizeDir',
                         'Map2Pangenome', 'ConvertSRA2Fastq', 'ConvertMap', 'ConvertMapwSingularity']},
      include_package_data=True,
      # install_requires=requirements,
      scripts=['bin/InvokeProkka', 'bin/InvokeRoary', 'bin/reorganizeDir',
               'bin/Map2Pangenome', 'bin/ConvertSRA2Fastq', 'bin/ConvertMap',
               'bin/ConvertMapwSingularity']
      # entry_points = {
      #     'console_scripts' : ['fetchnmap=map.cli:main'],
      #     }
      )