from setuptools import setup

# read requirements.
requirements = []
with open("requirements.txt", 'rU') as reader:
    for line in reader:
        requirements.append(line.strip())

setup(name='PangenomeAlignmentGenerator',
      python_requires='>=3',
      version='210111',
      description='align SRAs to a pangenome reference genome generated by Roary',
      url='https://github.com/apsteinberg/PangenomeAlignmentGenerator',
      license='MIT',
      author='Asher Preska Steinberg',
      author_email='apsteinberg@nyu.edu',
      packages=['bin'],
      package_data={'': ['InvokeProkka', 'InvokeRoary',
                         'ConvertMap', 'FetchGenomes']},
      include_package_data=True,
      install_requires=requirements,
      scripts=['bin/InvokeProkka', 'bin/InvokeRoary',
               'bin/ConvertMap', 'bin/FetchGenomes']
      # entry_points = {
      #     'console_scripts' : ['fetchnmap=map.cli:main'],
      #     }
      )